create database Project1

use Project1

create table Roles(
RoleID varchar(5) Primary key,
name varchar(50) not null unique,
Permissions varchar(100) not null,
);

create table Users(
ID int PRIMARY KEY Identity(1,1),
RoleID varchar(5) FOREIGN KEY REFERENCES [Roles](roleID),
email varchar(50) not null unique,
Username varchar(50) not null,
Password varchar(30) not null check(datalength([password])>=8),
);


create table Faculty (
ID int FOREIGN KEY REFERENCES [Users](ID),
F_Num varchar(5) primary key,
P_name varchar(30),
roll_num varchar(4) not null unique
);

create table Student (
S_ID int FOREIGN KEY REFERENCES [Users](ID),
S_name varchar(30),
roll_num varchar(7) NOT NULL Primary key,	
Group_ID varchar (5) not null 
);

create table FYP (
FYP_ID varchar(5) NOT NULL Primary key,
Title varchar(50),
description varchar(256),
Deadline date,
);

create table WorksOn(
roll_no varchar(7) FOREIGN KEY REFERENCES [Student](roll_num),
FYP_ID varchar(5)  FOREIGN KEY REFERENCES [FYP](FYP_ID),
);



create table supervises (
S_ID  VARCHAR(5) FOREIGN KEY REFERENCES [Faculty](F_Num),
Proj_ID  varchar(5) FOREIGN KEY REFERENCES [FYP](FYP_ID),
);

create table Evaluates (
S_ID  VARCHAR(5) FOREIGN KEY REFERENCES [Faculty](F_Num),
Proj_ID  varchar(5) FOREIGN KEY REFERENCES [FYP](FYP_ID),
Q1 varchar(4) ,
Q2 varchar(4) ,
Q3 varchar(4) ,
Q4 varchar(4) ,
Q5 varchar(4) ,
Q6 varchar(4) ,
Q7 varchar(4) ,
Q8 varchar(4) ,
Q9 varchar(4) ,
Q10 varchar(4) ,
Q11 varchar(4) ,
Q12 varchar(4) ,
Q13 varchar(4) ,
Q14 varchar(4) ,
Q15 varchar(4) ,
Review varchar(256),
GradeS varchar(4)
);



create table response
(
	Time_S time,
	Action varchar(500)

);
	
CREATE TRIGGER Insert_Audit
 ON response
 FOR 
 INSERT
 AS
 BEGIN
	INSERT INTO AuditTrail VALUES 
	(GETDATE(), 'Request Generated By Student');
END
CREATE TABLE AuditTrail
 (
	Time_Stamp DATETIME,
	Action_Taken VARCHAR(500)
 );